In [26]:
import requests
import pandas as pd

url = 'https://data.lacity.org/resource/5m3t-xjex.json?$select=ZIP_code,CD,permit_sub_type,permit_nbr,issue_date&$where=permit_type=%27HVAC%27&$limit=150000'

resp = requests.get(url)
data_frame =pd.DataFrame(resp.json())
data_frame.shape

(148630, 5)

In [7]:
data_frame.head()

,ZIP_code,CD,permit_sub_type,permit_nbr,issue_date
0,91316,5,1 or 2 Family Dwelling,17044-90000-11591,2017-09-12T00:00:00.000
1,91324,12,Commercial,18044-90000-00319,2018-01-10T00:00:00.000
2,90036,4,Commercial,13044-90000-04395,2013-04-29T00:00:00.000
3,91040,2,1 or 2 Family Dwelling,10044-40000-06868,2010-07-19T00:00:00.000
4,90026,13,Apartment,17044-10000-01747,2017-02-16T00:00:00.000

In [8]:
data_frame.dtypes

ZIP_code           str
CD                 str
permit_sub_type    str
permit_nbr         str
issue_date         str
dtype: object

In [6]:
data_frame['issue_date'] = pd.to_datetime(data_frame['issue_date'])
data_frame.dtypes

ZIP_code                      str
CD                            str
permit_sub_type               str
permit_nbr                    str
issue_date         datetime64[us]
dtype: object

In [10]:
data_frame['issue_date'].min(), data_frame['issue_date'].max()

(Timestamp('2010-01-03 00:00:00'), Timestamp('2019-12-31 00:00:00'))

In [11]:
data_frame.isnull().sum()

ZIP_code            13
CD                 113
permit_sub_type      0
permit_nbr           0
issue_date           0
dtype: int64

In [9]:
data_frame.isna().sum()

ZIP_code            13
CD                 113
permit_sub_type      0
permit_nbr           0
issue_date           0
dtype: int64

In [19]:
data_frame['permit_nbr'].duplicated().sum()

np.int64(0)

In [14]:
import requests
import pandas as pd

url = 'https://data.lacity.org/resource/67is-svtd.json?$select=ZIP_code,CD,permit_sub_type,permit_nbr,issue_date&$where=permit_type=%27HVAC%27&$limit=100000'
response = requests.get(url)
df = pd.DataFrame(response.json())
df.shape

(91571, 5)

In [15]:
df['issue_date'] = pd.to_datetime(df['issue_date'])

In [16]:
df['issue_date'].min(), df['issue_date'].max()

(Timestamp('2020-01-01 00:00:00'), Timestamp('2026-08-29 00:00:00'))

In [17]:
df.isnull().sum()

ZIP_code             2
CD                 335
permit_sub_type      0
permit_nbr           0
issue_date           0
dtype: int64

In [18]:
df['permit_nbr'].duplicated().sum()

np.int64(0)

In [11]:
df.head()

,ZIP_code,CD,permit_sub_type,permit_nbr,issue_date
0,91304,3,1 or 2 Family Dwelling,22044-90000-12301,2022-10-03T00:00:00.000
1,91324,12,1 or 2 Family Dwelling,26044-90000-04649,2026-04-28T00:00:00.000
2,90007,8,1 or 2 Family Dwelling,23044-90000-03150,2023-02-21T00:00:00.000
3,90025,11,Apartment,25044-90000-01116,2025-02-06T00:00:00.000
4,90068,4,1 or 2 Family Dwelling,21044-90000-05306,2021-05-27T00:00:00.000

In [12]:
df.dtypes

ZIP_code           str
CD                 str
permit_sub_type    str
permit_nbr         str
issue_date         str
dtype: object

In [13]:
df.isna().sum()

ZIP_code             2
CD                 335
permit_sub_type      0
permit_nbr           0
issue_date           0
dtype: int64

In [33]:
whole_f = pd.concat([data_frame, df], ignore_index = True)

In [35]:
whole_f.shape

(240201, 5)